/**
 * Instagram launch content — the single source for:
 *   docs/03b-instagram-first-30-posts.md   (the first 30 posts, in full)
 *   docs/04-content-calendar-90-days.md    (the 90-day calendar)
 *   docs/content-calendar.csv              (import into Sheets / Notion / Meta Business Suite)
 *
 * Regenerate after editing:  npm run calendar  (optionally  -- --start 2026-10-15)
 *
 * Anything in [square brackets] must be filled with something TRUE before
 * posting — founder details, real client names (with consent), real numbers.
 */

export const HANDLE = '@mithaiwallahofficial';

export const PILLARS = {
  making: { label: 'Sweet-making process', target: 0.4 },
  packaging: { label: 'Packaging', target: 0.2 },
  wedding: { label: 'Wedding gifting', target: 0.15 },
  corporate: { label: 'Corporate gifting', target: 0.1 },
  founder: { label: 'Founder journey', target: 0.1 },
  testimonial: { label: 'Customer testimonials & reactions', target: 0.05 },
};

export const TAGS = {
  core: ['#Mithaiwallah', '#PremiumSweets', '#IndianSweets', '#Mithai', '#HandcraftedSweets'],
  local: ['#Prayagraj', '#PrayagrajFood', '#Allahabad', '#UttarPradesh'],
  making: ['#SweetMaking', '#Halwai', '#SlowFood', '#FoodASMR', '#MadeByHand'],
  milkcake: ['#MilkCake', '#AlwarKaMawa', '#DesiGhee'],
  kalakand: ['#Kalakand', '#MilkSweets'],
  peda: ['#Peda', '#MathuraPeda', '#KesarPeda'],
  barfi: ['#MalaiBarfi', '#SilverVarq', '#Barfi'],
  kunda: ['#Kunda', '#CaramelisedMilk'],
  packaging: ['#LuxuryPackaging', '#GiftBox', '#Unboxing', '#PackagingDesign', '#SatisfyingVideo'],
  corporate: ['#CorporateGifting', '#CorporateGiftsIndia', '#DiwaliGifting', '#EmployeeGifts', '#ClientGifts'],
  wedding: ['#WeddingGifts', '#WeddingHampers', '#ReturnGifts', '#IndianWedding', '#ShaadiSeason', '#WeddingFavours'],
  festive: ['#Diwali2026', '#FestiveGifting', '#DiwaliSweets', '#FestiveHampers'],
  founder: ['#FounderStory', '#MadeInIndia', '#VocalForLocal', '#SmallBusinessIndia'],
};

const tags = (...sets) => [...new Set(sets.flatMap((s) => TAGS[s]))].join(' ');

/** The first 30 posts. Order = publishing order. */
export const FIRST_30 = [
  {
    format: 'Reel',
    pillar: 'making',
    title: 'Hours, not minutes — the milk cake film',
    hook: 'This milk cake took hours. Give us fifteen seconds.',
    script: [
      '0–2s  Slow-motion: full-cream milk pouring into a wide iron kadhai. On-screen text: the hook.',
      '2–5s  Overhead: the halwai’s ladle stirring, steam rising.',
      '5–8s  Macro: milk thickening and forming grain.',
      '8–11s The set slab is cut — the knife reveals the caramel centre (slow motion).',
      '11–14s A piece is placed with tongs into a maroon-and-gold box.',
      '14–15s End card: logo + “Handcrafted Traditions. Crafted for Celebrations.”',
      'Audio: slow instrumental (santoor or sitar-lofi). No voice-over.',
    ],
    caption:
      'Milk cake cannot be hurried. Full-cream milk, a wide kadhai, a patient hand — and hours of stirring until the centre turns to caramel and the edges stay golden and grainy.\n\nThis is Mithaiwallah. Handcrafted in Prayagraj. Welcome to our kitchen. 🤍',
    cta: 'Follow for the whole process — and tell us which sweet we should film next.',
    hashtags: tags('core', 'local', 'making', 'milkcake'),
  },
  {
    format: 'Carousel',
    pillar: 'making',
    title: 'Meet the Signature Six',
    hook: 'Six sweets. Each one made the long way.',
    script: [
      'Slide 1  Cover: all six on a brass thali, top-down. Text: the hook.',
      'Slide 2  Milk Cake — “Slow-caramelised, grainy, golden at the heart.”',
      'Slide 3  Kalakand — “Soft, moist, delicately grainy.”',
      'Slide 4  Malai Barfi — “Smooth ivory squares under silver varq.”',
      'Slide 5  Peda — “Khoya roasted in ghee to old gold.”',
      'Slide 6  Kunda — “Deep, dark, caramelised milk.”',
      'Slide 7  Bikaneri Cake — “Our richest cake, studded with dry fruits.”',
      'Slide 8  “Which one is going in your box? Comment 1–6.”',
    ],
    caption:
      'Our signature collection, introduced properly. Six sweets, pure milk solids, pure desi ghee and premium dry fruits — no shortcuts.\n\nWhich one are you picking first? Comment the number 👇',
    cta: 'Comment 1–6 · Save this for your next order.',
    hashtags: tags('core', 'local', 'milkcake', 'kalakand', 'peda', 'barfi'),
  },
  {
    format: 'Photo',
    pillar: 'corporate',
    title: 'Your logo, in gold foil',
    hook: 'Diwali corporate gifting is now booking.',
    script: [
      'Flat lay on a cream linen background: a maroon rigid box with a gold-foil logo (use a sample “YOUR LOGO” foil), ribbon slightly undone, one open box showing four sweets.',
      'Natural window light from the left; soft shadow. No text on the image except the foil.',
    ],
    caption:
      'Gifts that carry your name well.\n\nEmployee boxes, client hampers and leadership gifts — branded with your logo, packed by hand and delivered on your dates, anywhere in India.\n\nThe calm way to do Diwali: start eight weeks out. Our corporate team is booking now.',
    cta: 'DM “DIWALI” for the corporate catalogue, or tap the link in bio.',
    hashtags: tags('core', 'corporate', 'festive', 'local'),
  },
  {
    format: 'Reel',
    pillar: 'packaging',
    title: 'The most satisfying 12 seconds of our day',
    hook: 'The most satisfying 12 seconds of our day.',
    script: [
      '0–2s  Empty gold-lined tray drops into a maroon box (sound: soft thud).',
      '2–6s  Sweets placed one by one with tongs — each placement on a beat.',
      '6–8s  Silver varq laid over malai barfi (macro).',
      '8–10s Lid closes; ribbon pulled tight.',
      '10–12s Wax/foil seal pressed. End card.',
      'Audio: ASMR — real sounds only, amplified. No music.',
    ],
    caption: 'Packed by hand. Every. Single. Box. 🎁\n\nSound on for the ribbon.',
    cta: 'Send this to the person who always brings the best mithai.',
    hashtags: tags('core', 'packaging', 'making'),
  },
  {
    format: 'Carousel',
    pillar: 'founder',
    title: 'Why we started Mithaiwallah',
    hook: 'Why would anyone start a sweets company in 2026?',
    script: [
      'Slide 1  Founder photo in the kitchen. Text: the hook.',
      'Slide 2  “Because the box that carries our sweets deserved better.” [Founder: replace with your real reason in one line.]',
      'Slide 3  “[Where you grew up / first memory of mithai — true detail].”',
      'Slide 4  “We make six sweets. We make them slowly. We make them in Prayagraj.”',
      'Slide 5  “Our three non-negotiables: full-cream milk, pure desi ghee, no premixes.”',
      'Slide 6  “Follow along — we are building this in public.”',
    ],
    caption:
      'Hi, I’m [Founder name], and I started Mithaiwallah because [true reason, 2–3 sentences].\n\nThis account is where we’ll show you everything — the kitchen, the mistakes, the orders that go out at 2 a.m. before Diwali. Glad you’re here.',
    cta: 'Follow to build this with us. Ask me anything in the comments.',
    hashtags: tags('core', 'founder', 'local'),
  },
  {
    format: 'Photo',
    pillar: 'making',
    title: 'Kalakand, made this morning',
    hook: 'Made this morning. Gone by tonight.',
    script: ['Macro, 45°: a cut block of kalakand showing its moist grain, pistachio slivers on top. Shallow depth of field, warm light.'],
    caption:
      'Kalakand is only as good as the morning’s milk. Fresh chhena, slowly reduced milk, cardamom and pistachio — set soft, never dry.\n\nWe make it to order, because kalakand does not wait.',
    cta: 'Tag someone who would finish this box on the way home.',
    hashtags: tags('core', 'kalakand', 'local', 'making'),
  },
  {
    format: 'Reel',
    pillar: 'making',
    title: '5 a.m. in our kitchen',
    hook: 'Before Prayagraj wakes up, our kadhais are already warm.',
    script: [
      '0–3s  Dark exterior, lights on inside. Text: the hook.',
      '3–6s  Milk cans arriving; quick quality check (lactometer/sample).',
      '6–10s Hairnets, gloves, hand-wash — the routine.',
      '10–15s Burners lit, first milk into the kadhai, the first stir.',
      '15–18s Sunrise through the window; end card “Every day starts here.”',
      'Audio: ambient kitchen sound + soft music bed.',
    ],
    caption:
      'Every box starts here, long before the city is up. Fresh milk checked on arrival, a clean kitchen, and the first stir of the day.\n\nThis is the part nobody sees — so we thought we’d show you.',
    cta: 'Follow for more from inside the kitchen.',
    hashtags: tags('core', 'making', 'local'),
  },
  {
    format: 'Carousel',
    pillar: 'making',
    title: 'Milk cake vs kalakand — what’s the difference?',
    hook: 'You’ve eaten both. Can you tell them apart?',
    script: [
      'Slide 1  Split image: milk cake | kalakand. Text: the hook.',
      'Slide 2  How it’s made — milk cake: long reduction, caramelised. Kalakand: chhena + reduced milk, taken off early.',
      'Slide 3  Colour & texture side by side.',
      'Slide 4  Flavour: deep caramel vs fresh milk.',
      'Slide 5  Shelf life: ~10 days vs ~3 days refrigerated.',
      'Slide 6  Which to gift when: travel → milk cake; close to home → kalakand.',
      'Slide 7  “Team Milk Cake or Team Kalakand?”',
    ],
    caption: 'The great mithai debate, settled with facts. Full guide on our Journal (link in bio).',
    cta: 'Comment your team 👇 and save this for your next sweet-shop argument.',
    hashtags: tags('core', 'milkcake', 'kalakand', 'making'),
  },
  {
    format: 'Photo',
    pillar: 'wedding',
    title: 'Return gifts, with your names on them',
    hook: 'The last thing your guests take home should be the sweetest.',
    script: ['Rows of ivory return-gift boxes on a table, maroon ribbons, a foil monogram “A & R” (sample). Marigold petals scattered. Shot from a low angle so the rows recede.'],
    caption:
      'Return gifts designed around your wedding — your colours, your monogram, a message from the two families. Wedding season bookings are open.',
    cta: 'DM “WEDDING” for our wedding catalogue.',
    hashtags: tags('core', 'wedding', 'local'),
  },
  {
    format: 'Reel',
    pillar: 'making',
    title: 'Every peda carries a thumbprint',
    hook: 'Look closely at your peda. That’s a thumbprint.',
    script: [
      '0–3s  Macro: a finished peda, thumbprint in focus. Text: the hook.',
      '3–8s  Khoya roasting in ghee, turning gold.',
      '8–12s Halwai rolling a ball of khoya between palms (slow motion).',
      '12–15s The thumb presses the centre; a saffron strand goes in.',
      '15–17s Rows of pedas on a tray. End card.',
    ],
    caption:
      'Not decoration — a signature. Every peda we make is shaped by hand, one at a time, and every one carries the mark of the hand that made it.',
    cta: 'Save this. Share it with someone who takes peda for granted.',
    hashtags: tags('core', 'peda', 'making', 'local'),
  },
  {
    format: 'Carousel',
    pillar: 'packaging',
    title: 'Navratri gifting, nine ways',
    hook: 'Nine days of visits. Here’s what to take.',
    script: [
      'Slide 1  Cover: small boxes arranged in a 3×3 grid. Text: the hook.',
      'Slides 2–9  One box idea per slide — puja box, office aarti box, family visit box, kanya pujan return gift, etc.',
      'Slide 10 “Order by [date] for delivery in Prayagraj.”',
    ],
    caption: 'Navratri begins. Small, beautiful boxes for pujas, office aartis and every family visit. 🪔',
    cta: 'DM to order · Link in bio.',
    hashtags: tags('core', 'packaging', 'festive', 'local'),
  },
  {
    format: 'Photo',
    pillar: 'corporate',
    title: 'What planning ahead looks like',
    hook: 'When you plan eight weeks ahead, dispatch day looks like this.',
    script: ['A neat wall of identical branded boxes, labelled by city, ready for dispatch. Shoot only a REAL order (with the client’s permission) — never stage volume that doesn’t exist.'],
    caption:
      'No panic, no substitutions, no “we ran out of boxes.” Just [number] identical gifts, labelled by city, leaving on time.\n\nCorporate Diwali orders are booking now.',
    cta: 'HR & admin teams: DM “DIWALI” for the catalogue.',
    hashtags: tags('core', 'corporate', 'festive'),
  },
  {
    format: 'Reel',
    pillar: 'testimonial',
    title: 'Open it without knowing what’s inside',
    hook: 'We handed strangers a box and said nothing.',
    script: [
      '0–2s  Street/office setting, a box handed over. Text: the hook.',
      '2–12s Quick cuts of genuine reactions: lid lifts, “wow”, first bite, eyes close.',
      '12–15s Someone asks “Where is this from?” — end card with handle.',
      'Film real people with signed consent. Do not script or pay for reactions without disclosing it.',
    ],
    caption: 'Real reactions, first bite. The kalakand got the loudest “oh.” 😄',
    cta: 'Would you open it on camera? Tell us who to surprise next.',
    hashtags: tags('core', 'local', 'packaging'),
  },
  {
    format: 'Carousel',
    pillar: 'packaging',
    title: 'Anatomy of a Mithaiwallah gift box',
    hook: 'Everything that goes into a box before the sweets do.',
    script: [
      'Slide 1  Exploded flat lay of all components. Text: the hook.',
      'Slide 2  Rigid board box — it holds its shape across the country.',
      'Slide 3  Gold foil — your logo or monogram.',
      'Slide 4  Food-grade tray with cavities — nothing moves in transit.',
      'Slide 5  Sealed inner pack — freshness, and a batch code.',
      'Slide 6  Message card — English, Hindi or both.',
      'Slide 7  Ribbon + seal.',
      'Slide 8  “Build yours” CTA.',
    ],
    caption: 'A gift should feel like one before the lid is lifted. Here’s how we make sure it does.',
    cta: 'Save for your next gifting brief.',
    hashtags: tags('core', 'packaging', 'corporate'),
  },
  {
    format: 'Photo',
    pillar: 'making',
    title: 'Silver varq, one sheet at a time',
    hook: 'The quiet one on the platter.',
    script: ['Top-down macro of malai barfi squares with silver varq catching the light; a few pistachio slivers. Dark maroon background for contrast.'],
    caption: 'Malai barfi: fresh cream and khoya, smooth ivory squares, finished with edible silver varq. Richer than it looks.',
    cta: 'Double-tap if malai barfi is underrated.',
    hashtags: tags('core', 'barfi', 'making'),
  },
  {
    format: 'Reel',
    pillar: 'making',
    title: 'Kunda: milk, taken to its darkest',
    hook: 'Most sweetmakers stop here. We keep going.',
    script: [
      '0–3s  Pale reducing milk in the kadhai. Text: the hook.',
      '3–10s Time-lapse: milk darkens from cream to gold to deep brown.',
      '10–14s Glossy spoonful lifted in slow motion.',
      '14–16s Served warm in a brass katori. End card: “Kunda.”',
    ],
    caption: 'Kunda is milk and khoya cooked past the point where most sweets stop — until it turns deep, glossy and grainy. Try it warm, over vanilla ice cream. You’re welcome.',
    cta: 'Comment “KUNDA” if you’ve never tried it — we’ll tell you where to start.',
    hashtags: tags('core', 'kunda', 'making'),
  },
  {
    format: 'Carousel',
    pillar: 'corporate',
    title: 'The Diwali gifting checklist for HR teams',
    hook: 'HR teams: screenshot this before your Diwali meeting.',
    script: [
      'Slide 1  Text: the hook.',
      'Slide 2  8 weeks out: headcount, budget per box, cities.',
      'Slide 3  6 weeks: taste samples.',
      'Slide 4  4 weeks: approve the branded proof + address list.',
      'Slide 5  2 weeks: production.',
      'Slide 6  Festival week: tracked delivery.',
      'Slide 7  Bonus: 3 budget tiers (team / leadership / key clients).',
      'Slide 8  “Want the catalogue? DM CHECKLIST.”',
    ],
    caption: 'The difference between a gift people remember and one they forget is rarely the budget. It’s the calendar.',
    cta: 'DM “CHECKLIST” and we’ll send the corporate catalogue.',
    hashtags: tags('core', 'corporate', 'festive'),
  },
  {
    format: 'Photo',
    pillar: 'founder',
    title: 'The founder, in the kitchen',
    hook: '“[One-line founder quote — true and specific].”',
    script: ['Environmental portrait: the founder at the kadhai with the halwai team, sleeves rolled up, candid. Quote overlaid on the second image if posted as a two-image post.'],
    caption: '[Founder name] on why we make only six sweets: “[true quote, 2–3 lines].”',
    cta: 'Ask the founder anything 👇',
    hashtags: tags('core', 'founder', 'local'),
  },
  {
    format: 'Reel',
    pillar: 'packaging',
    title: 'Your logo, in gold — watch it happen',
    hook: 'Your logo, in gold. Watch it happen.',
    script: [
      '0–3s  A plain maroon lid on the foil press. Text: the hook.',
      '3–7s  The press comes down (slow motion, sound on).',
      '7–10s Lift reveals the shining foil logo (use a sample logo, not a client’s without permission).',
      '10–14s Box assembled with sweets. End card: “Custom branding available.”',
    ],
    caption: 'Every corporate box can carry your identity — on the lid, a sleeve, a message card, or all three. Approved on a proof before we press a single one.',
    cta: 'DM “LOGO” to see your brand on a Mithaiwallah box.',
    hashtags: tags('core', 'packaging', 'corporate'),
  },
  {
    format: 'Carousel',
    pillar: 'testimonial',
    title: 'Dussehra: who are you sharing this box with?',
    hook: 'Victory tastes sweeter shared.',
    script: [
      'Slide 1  A family festive box, open, marigolds around. Text: the hook.',
      'Slides 2–5  Each slide names a person: “the neighbour who always sends sweets back”, “the colleague who covered for you”, etc.',
      'Slide 6  “Tag them. We’ll pick one tag to send a box to.” (Run as a transparent giveaway with stated rules.)',
    ],
    caption: 'Happy Dussehra from Mithaiwallah. 🏹 Tag the person you’d share this box with — we’ll send one box to a tagged pair this week (rules in the last slide).',
    cta: 'Tag someone · Follow · Share to stories.',
    hashtags: tags('core', 'festive', 'local'),
  },
  {
    format: 'Photo',
    pillar: 'wedding',
    title: 'The invitation that arrives with sweets',
    hook: 'Some invitations you read. This one you taste.',
    script: ['Flat lay: a wedding card resting on an open invitation box (four sweets), marigold and rose petals, gold ribbon. Warm, festive styling.'],
    caption: 'A mithai box that carries your wedding card — often the thing guests remember first. Designed around your colours, printed with your names.',
    cta: 'DM “WEDDING” to plan your invitation boxes.',
    hashtags: tags('core', 'wedding'),
  },
  {
    format: 'Reel',
    pillar: 'making',
    title: 'Count the almonds',
    hook: 'Count the almonds. We dare you.',
    script: [
      '0–2s  A whole Bikaneri cake slab. Text: the hook.',
      '2–6s  Slow-motion cut through the slab.',
      '6–10s Macro pan across the cut face — almonds, cashews, pistachios.',
      '10–13s A thick slice on a plate. End card.',
    ],
    caption: 'Bikaneri Cake: our milk cake’s richer cousin — set thicker, cooked darker and layered with almonds, cashews and pistachios.',
    cta: 'Comment your count 👇',
    hashtags: tags('core', 'milkcake', 'making'),
  },
  {
    format: 'Carousel',
    pillar: 'wedding',
    title: 'How many boxes does your wedding need?',
    hook: 'Planning a wedding? Save this before you order a single box.',
    script: [
      'Slide 1  Text: the hook.',
      'Slide 2  Invitation boxes → count households, not heads.',
      'Slide 3  Family hampers → close-family households + 2–3 spare.',
      'Slide 4  Return gifts → one per household or couple, +5%.',
      'Slide 5  Example: 300 guests ≈ [x] households → [y] boxes. (Fill with a worked example.)',
      'Slide 6  Book as soon as the date is fixed.',
      'Slide 7  “DM WEDDING for a plan.”',
    ],
    caption: 'The maths nobody tells you about wedding sweets — simplified. Full guide on our Journal.',
    cta: 'Save + send to the person managing the guest list.',
    hashtags: tags('core', 'wedding'),
  },
  {
    format: 'Photo',
    pillar: 'making',
    title: 'The hands behind every box',
    hook: 'The hands behind every box.',
    script: ['Black-and-white or warm close-up of a halwai’s hands working fresh khoya. Name and years of experience in the caption — with their consent.'],
    caption: 'Meet [halwai name], who has been making sweets for [true number] years. Every tray you receive has passed through hands like these.',
    cta: 'Say hello to [name] in the comments 🙏',
    hashtags: tags('core', 'making', 'local'),
  },
  {
    format: 'Reel',
    pillar: 'wedding',
    title: 'Building a wedding hamper',
    hook: 'Building a wedding hamper for [A & R] (with their permission).',
    script: [
      '0–2s  Empty velvet-lined trunk. Text: the hook.',
      '2–10s Hands add sweets, dry fruits, a brass diya, a monogrammed card — one item per beat.',
      '10–13s Lid closes; ribbon in the couple’s colours.',
      '13–15s End card: “Designed around your wedding.”',
    ],
    caption: 'Every family hamper is built around the wedding it belongs to — colours, names, and the sweets the family actually loves.',
    cta: 'DM “WEDDING” to design yours.',
    hashtags: tags('core', 'wedding', 'packaging'),
  },
  {
    format: 'Carousel',
    pillar: 'making',
    title: 'From milk to milk cake in 7 steps',
    hook: 'From milk to milk cake, in 7 steps.',
    script: [
      'Slide 1  Cover: milk jug + finished slab. Text: the hook.',
      'Slides 2–8  One step per slide: milk arrives & tested → reduction begins → grain forms → sugar → caramelisation → set & rest → cut, pack, dispatch.',
      'Slide 9  “Now you know why it’s worth it.”',
    ],
    caption: 'No premix. No shortcuts. Just milk, time and a patient hand.',
    cta: 'Save and share with someone who thinks milk cake is “just a sweet.”',
    hashtags: tags('core', 'making', 'milkcake'),
  },
  {
    format: 'Photo',
    pillar: 'packaging',
    title: 'The Royal Trunk',
    hook: 'For the relationships that matter most.',
    script: ['Hero product shot of the velvet-lined keepsake trunk, half open, lit like jewellery — dark background, single key light, gold reflections.'],
    caption: 'The Royal Trunk: Bikaneri cake, the signature sweets, premium dry fruits and a keepsake — in a velvet-lined trunk made to be kept long after the sweets are gone.',
    cta: 'For leadership and key-client gifting — DM “ROYAL”.',
    hashtags: tags('core', 'packaging', 'corporate', 'wedding'),
  },
  {
    format: 'Reel',
    pillar: 'founder',
    title: 'Three things I will never compromise on',
    hook: 'Three things I will never compromise on.',
    script: [
      'Talking head, founder in the kitchen, B-roll cut-ins.',
      '1. “Full-cream milk.” (B-roll: milk pour)',
      '2. “Pure desi ghee.” (B-roll: ghee spoon)',
      '3. “[Founder’s own third point — true].” (B-roll to match)',
      'Close: “That’s Mithaiwallah.” End card.',
      'Keep under 25s. Burned-in captions.',
    ],
    caption: 'Some things are cheaper. They’re just not ours. — [Founder name]',
    cta: 'What’s your non-negotiable in your work? Tell me below.',
    hashtags: tags('core', 'founder', 'making'),
  },
  {
    format: 'Carousel',
    pillar: 'packaging',
    title: 'Last week to book branded Diwali orders',
    hook: 'Karva Chauth today. Diwali in 10 days. Have you ordered?',
    script: [
      'Slide 1  Text: the hook, over a box shot.',
      'Slide 2  “Branded corporate orders: last confirmations this week.” [Adjust to real capacity.]',
      'Slide 3  “Family festive boxes: order by [date] for delivery in Prayagraj.”',
      'Slide 4  “Pan-India: order by [date].”',
      'Slide 5  The three collections.',
      'Slide 6  “DM or tap the link in bio.”',
    ],
    caption: 'Happy Karva Chauth 🌙 — and a gentle nudge: Diwali is ten days away. Here’s what can still be done in time.',
    cta: 'DM “DIWALI” · Link in bio.',
    hashtags: tags('core', 'festive', 'packaging', 'corporate'),
  },
  {
    format: 'Photo',
    pillar: 'making',
    title: 'The Diwali thali',
    hook: 'Nine days to Diwali.',
    script: ['Top-down: a brass thali with all six sweets, diyas lit around it, rangoli edge in frame. Shoot at dusk for real diya light.'],
    caption: 'Nine days to Diwali. Six sweets, made the long way, for the brightest night of the year. 🪔',
    cta: 'Order your festive box — link in bio.',
    hashtags: tags('core', 'festive', 'local'),
  },
];

/**
 * Idea bank for days 31–90. The calendar generator draws from each pillar in
 * the ratio of PILLARS[*].target, taking the least-used idea first. `format`
 * is the preferred format — most ideas can be shot as a Reel or a Carousel,
 * and the generator will re-cut one if the slot needs it. `from` / `to` keep
 * seasonal ideas in season (ISO dates, inclusive).
 */
const PRODUCTS = ['Milk Cake', 'Kalakand', 'Malai Barfi', 'Peda', 'Kunda', 'Bikaneri Cake'];
const MAKING_ANGLES = [
  ['slow-motion pour & first stir', 'Reel', 'Watch this milk turn into {p}.'],
  ['the cut reveal', 'Reel', 'The cut you didn’t know you needed.'],
  ['garnish close-up', 'Reel', 'The finishing touch on {p}.'],
  ['texture macro (ASMR)', 'Reel', 'Sound on. This is {p}.'],
  ['halwai’s tip', 'Reel', 'A halwai’s secret for perfect {p}.'],
  ['how to serve it', 'Carousel', '3 ways to serve {p} like a host.'],
  ['ingredient story', 'Carousel', 'What actually goes into {p}.'],
  ['myth vs fact', 'Carousel', '{p}: 4 things people get wrong.'],
  ['hero still', 'Photo', '{p}. That’s it. That’s the post.'],
];
const idea = ([title, format, hook, from, to]) => ({ title, format, hook, from, to });

export const BANK = {
  making: [
    ...PRODUCTS.flatMap((p) => MAKING_ANGLES.map(([angle, format, hook]) => ({ title: `${p}: ${angle}`, format, hook: hook.replace('{p}', p) }))),
    ...[
      ['Factory tour: 60 seconds, milk to box', 'Reel', 'Our whole kitchen in 60 seconds.'],
      ['Quality check: what we test and why', 'Carousel', 'What happens to milk before it becomes mithai.'],
      ['Winter menu: warm kunda and more', 'Reel', 'Winter was made for warm kunda.', '2026-11-20'],
      ['Mithai glossary: khoya, chhena, malai, varq', 'Carousel', 'The mithai words everyone uses and nobody explains.'],
      ['Regional sweets map: where our six come from', 'Carousel', 'Six sweets, six stories of India.'],
    ].map(idea),
  ],
  packaging: [
    ['ASMR box packing — a different sweet each time', 'Reel', 'Packed by hand. Sound on.'],
    ['Ribbon-tying close-up', 'Reel', 'One ribbon. Zero shortcuts.'],
    ['Foil logo stamping for a (consenting) client', 'Reel', 'This logo just went gold.'],
    ['Custom sleeve printing: proof → final', 'Carousel', 'From proof to box in 4 slides.'],
    ['Dispatch day, city by city', 'Reel', 'Where are these boxes going?'],
    ['Unboxing POV', 'Reel', 'POV: this just arrived at your desk.'],
    ['Tray layouts: 4, 6 or 9 cavities', 'Carousel', 'Pick your layout.'],
    ['Writing the message cards', 'Reel', 'Every card, written like it matters.'],
    ['The three collections side by side', 'Photo', 'Classic, Heritage or Royal?'],
    ['Packing for a 1,500 km journey', 'Carousel', 'How our sweets survive a 1,500 km journey.'],
    ['Box colour stories: maroon, ivory, gold', 'Carousel', 'Three colours, three moods.'],
    ['Sustainable choices in our packaging', 'Carousel', 'What happens to your box after the sweets are gone.'],
    ['Build-a-box: viewers pick the assortment', 'Reel', 'You pick, we pack.'],
    ['Diwali box countdown', 'Reel', 'Days to Diwali. Boxes to pack.', undefined, '2026-11-07'],
    ['Christmas & New Year box reveal', 'Reel', 'The year-end box is here.', '2026-12-01'],
  ].map(idea),
  wedding: [
    ['Monogram reveal on a return-gift box', 'Reel', 'Their initials, in gold.'],
    ['Return-gift table set-up at a venue', 'Reel', 'The last thing guests see before they leave.'],
    ['Colour-matching session with a bride’s family', 'Reel', 'Matching the lehenga, one ribbon at a time.'],
    ['Tasting session with two families', 'Reel', 'The happiest hour of wedding planning.'],
    ['Wedding planner collab: 3 favour trends', 'Carousel', '3 wedding favour trends planners love this season.'],
    ['Baraat box', 'Photo', 'For the baraat.'],
    ['Shagun box with envelope slot', 'Photo', 'Shagun, sweetened.'],
    ['Destination-wedding hamper packing', 'Carousel', 'How we ship hampers to a destination wedding.'],
    ['Wedding sweets by ceremony: roka to bidaai', 'Carousel', 'A box for every ceremony.'],
    ['Wedding gifting mistakes to avoid', 'Carousel', '5 wedding gifting mistakes (and how to avoid them).'],
    ['Budgeting wedding boxes', 'Carousel', 'What wedding boxes really cost — and where to save.'],
    ['Wedding season is open', 'Reel', 'Shaadi season starts now.', '2026-11-18'],
    ['Real wedding feature (with the couple’s consent)', 'Carousel', 'Inside [couple]’s wedding boxes.'],
    ['Elders’ box: softer sweets, bigger love', 'Photo', 'For the elders at the wedding.'],
  ].map(idea),
  corporate: [
    ['Logo proof → foil → finished box', 'Reel', 'From your logo file to this.'],
    ['Three gifting tiers explained', 'Carousel', 'Team, leadership, key clients: how to budget.'],
    ['Bulk dispatch time-lapse (real order)', 'Reel', '[N] boxes. One afternoon.'],
    ['New Year client gifting', 'Carousel', 'The client gift that isn’t another diary.', '2026-11-12'],
    ['Office delivery day', 'Reel', 'When the Mithaiwallah boxes arrive at the office.'],
    ['Employee milestone gifting', 'Photo', 'Work anniversaries deserve better than an email.'],
    ['Corporate gifting FAQ', 'Carousel', 'Your corporate gifting questions, answered.'],
    ['Plan next Diwali now: the 2027 early-bird list', 'Carousel', 'Next Diwali, without the panic.', '2026-11-15'],
    ['Onboarding boxes for new joiners', 'Photo', 'Day one, sweetened.'],
  ].map(idea),
  founder: [
    ['A day in the founder’s life in Diwali week', 'Reel', 'Diwali week, as a sweets founder.', '2026-11-01', '2026-11-12'],
    ['Biggest mistake so far', 'Reel', 'The mistake that cost us [x] — and what we changed.'],
    ['Prayagraj roots', 'Carousel', 'Why Prayagraj.'],
    ['Founder Q&A from comments', 'Reel', 'You asked. I answered.'],
    ['Meet the team', 'Carousel', 'The people behind every box.'],
    ['Lessons from the first festive season', 'Carousel', 'What our first Diwali taught us.', '2026-11-12'],
    ['Why only six sweets', 'Reel', 'Why we say no to a hundred sweets.'],
    ['Numbers we are proud of (real ones only)', 'Carousel', '[Real milestone] — thank you.'],
    ['The halwai who taught me', 'Reel', 'The person who taught me what good mithai is.'],
  ].map(idea),
  testimonial: [
    ['Client reaction video (with consent)', 'Reel', 'We asked [client] what their team said.'],
    ['Planner review', 'Photo', '“[Real quote].”'],
    ['Customer unboxing reshare', 'Reel', 'Your unboxings are our favourite content.'],
    ['DM screenshots (with permission, names hidden)', 'Carousel', 'Messages that made our week.'],
    ['Hotel chef on consistency', 'Reel', 'Why [hotel] trusts us with their buffet.'],
  ].map(idea),
};

/** Fixed-date anchors inside a typical October–December launch window. */
export const FESTIVALS = [
  { date: '2026-10-11', name: 'Navratri begins', pillar: 'packaging' },
  { date: '2026-10-20', name: 'Dussehra', pillar: 'testimonial' },
  { date: '2026-10-29', name: 'Karva Chauth', pillar: 'packaging' },
  { date: '2026-11-06', name: 'Dhanteras', pillar: 'packaging' },
  { date: '2026-11-08', name: 'Diwali', pillar: 'making' },
  { date: '2026-11-10', name: 'Bhai Dooj (10–11 Nov by region)', pillar: 'packaging' },
  { date: '2026-12-25', name: 'Christmas', pillar: 'corporate' },
];

export const CTA_BY_PILLAR = {
  making: 'Save + follow for the process',
  packaging: 'DM to order · link in bio',
  wedding: 'DM “WEDDING” for the catalogue',
  corporate: 'DM “DIWALI” / “GIFTING” for the catalogue',
  founder: 'Ask the founder anything',
  testimonial: 'Tag someone · share your unboxing',
};

export const TAGSET_BY_PILLAR = {
  making: ['core', 'making', 'local'],
  packaging: ['core', 'packaging'],
  wedding: ['core', 'wedding'],
  corporate: ['core', 'corporate'],
  founder: ['core', 'founder', 'local'],
  testimonial: ['core', 'local'],
};

export { tags };
