/**
 * Emits every derived table the DPR and pitch deck consume.
 *
 *   node investor/build.mjs
 *
 * Writes investor/output/model.json (machine-readable, for the deck) and
 * investor/output/tables.md (human-readable, pasted into the DPR).
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import * as M from './model.mjs';

mkdirSync(new URL('./output/', import.meta.url), { recursive: true });

const scenarios = ['conservative', 'base', 'aggressive'];

const model = {
  meta: { ...M.META, generatedAt: new Date().toISOString().slice(0, 10) },
  tax: M.TAX,
  market: M.marketSizing(),
  marketRefs: M.MARKET,
  channels: M.channelTable(),
  unitEconomics: {
    can250: [0, 1, 2, 3, 4].map((y) => M.unitEconomics('can250', y)),
    byFormatY1: ['can250', 'can300', 'can330'].map((f) => M.unitEconomics(f, 0)),
    byFormatY5: ['can250', 'can300', 'can330'].map((f) => M.unitEconomics(f, 4)),
    minimumViablePrice: ['can250', 'can300', 'can330'].map((f) => ({
      format: M.FORMATS[f].label,
      currentMrp: M.FORMATS[f].mrp,
      ...M.minimumViablePrice(f, 0, 0.5),
    })),
  },
  costBreakdown: {
    y1: M.FORMATS.can250.costBreakdownY1,
    y5: M.FORMATS.can250.costBreakdownY5,
  },
  pnl: Object.fromEntries(scenarios.map((s) => [s, M.buildPnl(s)])),
  ltv: Object.fromEntries(scenarios.map((s) => [s, M.ltvAnalysis(s)])),
  capTable: M.capTable().stages,
  returns: Object.fromEntries(scenarios.map((s) => [s, M.returns(s)])),
  probabilityWeighted: M.probabilityWeightedSeedReturn(),
  adoption: M.adoptionCurve('base'),
};

writeFileSync(new URL('./output/model.json', import.meta.url), JSON.stringify(model, null, 2));

/* ── Markdown emitter ───────────────────────────────────────────────────── */

const md = (rows, cols) => {
  const head = `| ${cols.map((c) => c.h).join(' | ')} |`;
  const sep = `|${cols.map(() => '---').join('|')}|`;
  const body = rows.map((r) => `| ${cols.map((c) => c.f(r)).join(' | ')} |`).join('\n');
  return [head, sep, body].join('\n');
};

const cr = (n) => `₹${n.toFixed(2)} Cr`;
const pct = (n) => `${n.toFixed(1)}%`;
const inr = (n) => `₹${n.toLocaleString('en-IN')}`;

let out = `<!-- GENERATED by investor/build.mjs — do not edit by hand.
     Change investor/assumptions.mjs and re-run. -->

# FROLIC — Generated Model Tables

Model version ${M.META.modelVersion} · generated ${model.meta.generatedAt} · USD at ₹${M.META.usdInr}

`;

out += `## 1. Channel economics — 250 ml can at MRP ₹${M.FORMATS.can250.mrp}\n\n`;
out += `GST of ${(M.TAX.carbonatedGst * 100).toFixed(0)}% is deducted before any participant in the value chain is paid.\n\n`;
out += md(model.channels, [
  { h: 'Channel', f: (r) => r.channel },
  { h: 'MRP', f: (r) => inr(r.mrp) },
  { h: 'GST', f: (r) => `−${inr(r.gst)}` },
  { h: 'Ex-GST', f: (r) => inr(r.exGst) },
  { h: 'Trade + platform', f: (r) => `−${inr(r.tradeAndPlatform)}` },
  { h: 'Logistics', f: (r) => `−${inr(r.logistics)}` },
  { h: 'Net to brand', f: (r) => `**${inr(r.netToBrand)}**` },
  { h: '% of MRP', f: (r) => pct(r.netAsPctOfMrp) },
]);

out += `\n\n## 2. Unit economics — 250 ml, by year\n\n`;
out += md(model.unitEconomics.can250, [
  { h: 'Year', f: (_, i) => '' },
  { h: 'Blended net realisation', f: (r) => inr(r.blendedNetRealisation) },
  { h: 'COGS', f: (r) => inr(r.cogs) },
  { h: 'Contribution', f: (r) => `**${inr(r.contributionPerCan)}**` },
  { h: 'Gross margin', f: (r) => pct(r.grossMarginPct) },
].map((c, i) => (i === 0 ? { h: 'Year', f: (r) => `Y${model.unitEconomics.can250.indexOf(r) + 1}` } : c)));

out += `\n\n## 3. Format comparison — Year 1\n\n`;
out += md(model.unitEconomics.byFormatY1, [
  { h: 'Format', f: (r) => r.format },
  { h: 'MRP', f: (r) => inr(r.mrp) },
  { h: 'GST/can', f: (r) => inr(r.gstPerCan) },
  { h: 'Net to brand', f: (r) => inr(r.blendedNetRealisation) },
  { h: 'COGS', f: (r) => inr(r.cogs) },
  { h: 'Contribution', f: (r) => `**${inr(r.contributionPerCan)}**` },
  { h: 'GM%', f: (r) => pct(r.grossMarginPct) },
]);

out += `\n\n## 4. Minimum viable selling price (50% GM floor, Year-1 costs)\n\n`;
out += md(model.unitEconomics.minimumViablePrice, [
  { h: 'Format', f: (r) => r.format },
  { h: 'Planned MRP', f: (r) => inr(r.currentMrp) },
  { h: 'Net required', f: (r) => inr(r.requiredNet) },
  { h: 'Minimum viable MRP', f: (r) => `**${inr(r.minimumViableMrp)}**` },
  { h: 'Headroom', f: (r) => pct(((r.currentMrp - r.minimumViableMrp) / r.currentMrp) * 100) },
]);

for (const s of scenarios) {
  const p = model.pnl[s];
  out += `\n\n## 5.${scenarios.indexOf(s) + 1} P&L — ${p.scenario} case\n\n`;
  out += `EBITDA positive in **Year ${p.ebitdaPositiveYear ?? '—'}** · peak cumulative operating burn **${cr(Math.abs(p.peakCumulativeBurnCr))}** · peak working capital **${cr(p.peakWorkingCapitalCr)}** · total capital need **${cr(p.totalCapitalNeedCr)}**\n\n`;
  out += md(p.years, [
    { h: 'Year', f: (r) => `Y${r.year}` },
    { h: 'Customers', f: (r) => r.customers.toLocaleString('en-IN') },
    { h: 'Cans', f: (r) => r.cans.toLocaleString('en-IN') },
    { h: 'ARPU', f: (r) => inr(r.arpu) },
    { h: 'Net revenue', f: (r) => cr(r.netRevenueCr) },
    { h: 'Gross margin', f: (r) => pct(r.grossMarginPct) },
    { h: 'Marketing', f: (r) => cr(r.marketingCr) },
    { h: 'Opex', f: (r) => cr(r.opexCr) },
    { h: 'EBITDA', f: (r) => `**${cr(r.ebitdaCr)}**` },
    { h: 'EBITDA %', f: (r) => pct(r.ebitdaMarginPct) },
    { h: 'Net profit', f: (r) => cr(r.netProfitCr) },
  ]);
}

out += `\n\n## 6. LTV / CAC — base case\n\n`;
out += md(model.ltv.base, [
  { h: 'Year', f: (r) => `Y${r.year}` },
  { h: 'CAC', f: (r) => inr(r.cac) },
  { h: 'Y1 contribution', f: (r) => inr(r.year1Contribution) },
  { h: '3-yr LTV', f: (r) => inr(r.threeYearLtv) },
  { h: 'LTV:CAC', f: (r) => `**${r.ltvToCac.toFixed(1)}×**` },
  { h: 'Payback', f: (r) => `${r.paybackMonths.toFixed(0)} mo` },
]);

out += `\n\n## 7. Cap table evolution\n\n`;
out += md(model.capTable.filter((s) => s.stage !== 'Founding'), [
  { h: 'Stage', f: (r) => r.stage },
  { h: 'Raise', f: (r) => (r.raiseCr ? cr(r.raiseCr) : '—') },
  { h: 'Post-money', f: (r) => (r.postMoneyCr ? cr(r.postMoneyCr) : '—') },
  { h: 'Founders', f: (r) => pct(r.founders) },
  { h: 'ESOP', f: (r) => pct(r.esop) },
  { h: 'Seed', f: (r) => (r.rows.find((x) => x.name === 'Seed') ? pct(r.rows.find((x) => x.name === 'Seed').pct) : '—') },
  { h: 'Series A', f: (r) => (r.rows.find((x) => x.name === 'Series A') ? pct(r.rows.find((x) => x.name === 'Series A').pct) : '—') },
  { h: 'Series B', f: (r) => (r.rows.find((x) => x.name === 'Series B') ? pct(r.rows.find((x) => x.name === 'Series B').pct) : '—') },
]);

for (const s of scenarios) {
  const r = model.returns[s];
  out += `\n\n## 8.${scenarios.indexOf(s) + 1} Investor returns — ${s} (Y7 revenue ${cr(r.y7RevenueCr)} × ${r.exitMultiple} = ${cr(r.exitValueCr)} / $${r.exitValueUsdMn}M)\n\n`;
  out += md(r.rows, [
    { h: 'Round', f: (x) => x.round },
    { h: 'Invested', f: (x) => cr(x.investedCr) },
    { h: 'Entry post-money', f: (x) => cr(x.entryPostMoneyCr) },
    { h: 'Final ownership', f: (x) => pct(x.finalOwnershipPct) },
    { h: 'Exit proceeds', f: (x) => cr(x.exitProceedsCr) },
    { h: 'MOIC', f: (x) => `**${x.moic.toFixed(1)}×**` },
    { h: 'IRR', f: (x) => pct(x.irrPct) },
  ]);
}

out += `\n\n## 9. Probability-weighted seed return\n\n`;
out += md(model.probabilityWeighted.outcomes, [
  { h: 'Outcome', f: (r) => r.name },
  { h: 'Probability', f: (r) => pct(r.probabilityPct) },
  { h: 'Seed proceeds', f: (r) => cr(r.proceedsCr) },
  { h: 'MOIC', f: (r) => `${r.moic.toFixed(1)}×` },
  { h: 'Weighted', f: (r) => cr(r.weightedCr) },
]);
out += `\n\n**Expected value: ${cr(model.probabilityWeighted.expectedProceedsCr)} on ₹10 Cr = ${model.probabilityWeighted.expectedMoic.toFixed(1)}× MOIC, ${pct(model.probabilityWeighted.expectedIrrPct)} IRR over 7 years.**\n`;

out += `\n\n## 10. Adoption curve — base case\n\n`;
out += md(model.adoption, [
  { h: 'Year', f: (r) => `Y${r.year}` },
  { h: 'Customers', f: (r) => r.customers.toLocaleString('en-IN') },
  { h: 'Penetration of beachhead', f: (r) => pct(r.penetrationOfBeachheadPct) },
  { h: 'Adopter band', f: (r) => r.adopterBand },
]);
out += `\n\nBeachhead = ${model.market.premiumBeverageBuyersMn.toFixed(1)}M premium-beverage buyers across ${model.market.cities.join(', ')}.\n`;

writeFileSync(new URL('./output/tables.md', import.meta.url), out);

console.log('Wrote investor/output/model.json and investor/output/tables.md');
console.log(`Base case: EBITDA+ Y${model.pnl.base.ebitdaPositiveYear}, Y5 ${cr(model.pnl.base.y5NetRevenueCr)}, capital need ${cr(model.pnl.base.totalCapitalNeedCr)}`);
console.log(`Seed expected: ${model.probabilityWeighted.expectedMoic.toFixed(1)}x MOIC / ${model.probabilityWeighted.expectedIrrPct.toFixed(1)}% IRR`);
